name: videoplayerapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  dio: ^5.3.3
  http: ^1.1.0
  retry: ^3.1.2
  video_player: ^2.8.1
  sizer: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  google_mobile_ads: ^3.1.0
  chewie: ^1.7.1
  flutter_native_splash: ^2.3.5
  share_plus: ^7.0.2
  external_app_launcher: ^3.1.0

flutter_native_splash:
  color: "#3A4C72"
  image: assets/images/splash.png
  android_12:
    color: "#3A4C72"
    image: assets/images/splash.png

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  
